"""Urls for SGI."""
from django.urls import path, re_path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    # De Django.
    re_path(r'^accounts/', include('django.contrib.auth.urls'), name='password_change'),
    path('', views.home, name='home'),
    path('logout/', views.custom_logout, name='logout'),
    # Trabajos.
    path('trabajos/', views.lista_reclamos, name='lista_reclamos'),
    path('trabajos/<int:pk>/', views.detalle_reclamo, name='detalle_reclamo'),
    path('trabajos/nuevo/', views.nuevo_reclamo, name='nuevo_reclamo'),
    path('trabajos/nuevo_r/', views.nuevo_reclamo_r, name='nuevo_reclamo_r'),
    path('trabajos/<int:pk>/editar/', views.editar_reclamo, name='editar_reclamo'),
    path('trabajos/borradores/', views.lista_reclamos_borradores, name='lista_reclamos_borradores'),
    path('trabajos/<pk>/grabar/', views.grabar_reclamo, name='grabar_reclamo'),
    path('trabajos/<pk>/eliminar_reclamo/', views.eliminar_reclamo, name='eliminar_reclamo'),
    path('trabajos/pendientes/', views.lista_reclamos_pendientes, name='lista_reclamos_pendientes'),
    path('trabajos/finalizados/', views.lista_reclamos_finalizados,
         name='lista_reclamos_finalizados'),
    path('trabajos/seguimiento/', views.lista_reclamos_seguimiento, name='lista_reclamos_seguir'),
    path('trabajos/deuda/', views.lista_reclamos_deuda, name='lista_reclamos_deuda'),
    path('trabajos/archivos/<pk>/carga_archivos/', views.carga_archivos, name='carga_archivos'),
    path('trabajos/archivos/<pk>/detalle_archivo/', views.detalle_archivo, name='detalle_archivo'),
    path('trabajos/archivos/<pk>/eliminar_archivo/', views.eliminar_archivo,
         name='eliminar_archivo'),
    path('trabajos/<int:pk>/imprimir_comprobante/', views.imprimir_comprobante_reclamo,
         name='imprimir_comprobante_reclamo'),
    # Cuadrillas vista.
    path('trabajos/cuadrillas/agua/', views.cuadrilla_agua, name='cuadrilla_agua'),
    path('trabajos/cuadrillas/cloacas/', views.cuadrilla_cloacas, name='cuadrilla_cloacas'),
    path('trabajos/cuadrillas/niv_pozos/', views.cuadrilla_niv_pozos, name='cuadrilla_niv_pozos'),
    path('trabajos/cuadrillas/marco_tapa/', views.cuadrilla_mco_tapa, name='cuadrilla_mco_tapa'),
    path('trabajos/cuadrillas/mant_cloacal/', views.cuadrilla_mant_cloacal, name='cuadrilla_mant_cloacal'),
    path('trabajos/cuadrillas/verif_fact/', views.cuadrilla_verif_fact, name='cuadrilla_verif_fact'),
    path('trabajos/cuadrillas/serv_med/', views.cuadrilla_rec_serv_med, name='cuadrilla_serv_med'),
    # Cuadrillas impresión.
    path('trabajos/cuadrillas/cuadrilla_agua/', views.imprimir_cuadrilla_agua,
         name='imprimir_cuadrilla_agua'),
    path('trabajos/cuadrillas/cuadrilla_cloacas/', views.imprimir_cuadrilla_cloacas,
         name='imprimir_cuadrilla_cloacas'),
    path('trabajos/cuadrillas/cuadrilla_pozos/', views.imprimir_cuadrilla_pozos,
         name='imprimir_cuadrilla_pozos'),
    path('trabajos/cuadrillas/cuadrilla_marco_tapa/', views.imprimir_cuadrilla_marco_tapa,
         name='imprimir_cuadrilla_marco_tapa'),
    path('trabajos/cuadrillas/cuadrilla_mant_red_cloacal/', views.imprimir_cuadrilla_mant_red_cloacal,
         name='imprimir_cuadrilla_mant_red_cloacal'),
    path('trabajos/cuadrillas/cuadrilla_verif_fact/', views.imprimir_cuadrilla_verif_fact,
         name='imprimir_cuadrilla_verif_fact'),
    path('trabajos/cuadrillas/cuadrilla_serv_med/', views.imprimir_cuadrilla_serv_med,
         name='imprimir_cuadrilla_serv_med'),

    path('datos_partida/', views.info_partida, name='info_partida'),
    path('api/buscar-partidas/', views.buscar_partidas_ajax, name='buscar_partidas_ajax'),
    path('api/toggle-a-reporte/', views.toggle_a_reporte, name='toggle_a_reporte'),
    path('api/lista-reclamos-ajax/', views.lista_reclamos_ajax, name='lista_reclamos_ajax'),
    re_path(r'^partida/partida-(?P<partida>\w+)/$', views.detalle_partida, name="detalle_partida"),
    path('trabajos/reportes/pend_fin/', views.rep_pend_fin, name='rep_pend_fin'),
    path('trabajos/reportes/tiem_resol/', views.rep_tiem_resol, name='rep_tiem_resol'),
    path('herramientas/conversor_rbc/', views.conversor_rbc, name='conversor_rbc'),
    path('herramientas/rend_alberghini/', views.rend_alberghini, name='rend_alberghini'),
    path('herramientas/ret_iibb/', views.ret_iibb, name='ret_iibb'),
    path('herramientas/perc_iibb/', views.perc_iibb, name='perc_iibb'),
    path('herramientas/listado_b_c/', views.listado_b_c, name='listado_b_c'),
    path('herramientas/filtro_pmc/', views.filtro_pmc, name='filtro_pmc'),
    path('herramientas/sicore/', views.sicore, name='sicore'),
    path('herramientas/alta_incob/', views.alta_incob, name='alta_incob'),
    path('herramientas/baja_incob/', views.baja_incob, name='baja_incob'),
    path('herramientas/liq_iibb/', views.liq_iibb, name='liq_iibb'),
    path('herramientas/pres_cuat_arba/', views.pres_cuat_arba, name='pres_cuat_arba'),
    path('herramientas/pres_cuat_arba_osebal/', views.pres_cuat_arba_osebal, name='pres_cuat_arba_osebal'),
    path('herramientas/deuda_proveedores/', views.deuda_proveedores, name='deuda_proveedores'),
    path('herramientas/carga_masivo_deuda/', views.carga_masivo_deuda, name='carga_masivo_deuda'),
    path('herramientas/carga_partidas_proveedores/',
         views.carga_partidas_proveedores, name='carga_partidas_proveedores'),
    path('herramientas/reporte_estado_deuda/', views.rd_generados, name='reporte_estado_deuda'),
    path('herramientas/reporte_sms_masivos/',
         views.reporte_sms_masivos, name='reporte_sms_masivos'),
    path('herramientas/dto_int_canon/', views.dto_int_canon, name='dto_int_canon'),
    path('herramientas/cort_dism_cons/', views.list_cort_dism, name='cort_dism_cons'),
    path('herramientas/libro_iva_digital/', views.libro_iva_digital_rend, name='libro_iva_digital'),

    # STOCK
    path('stock/nuevo_material/', views.nuevo_material, name='nuevo_material'),
    path('stock/listado_materiales/', views.listado_materiales, name='listado_materiales'),
    path('stock/<pk>/grabar_material/', views.grabar_material, name='grabar_material'),
    path('stock/<pk>/detalle_material/', views.detalle_material, name='detalle_material'),
    path('stock/<pk>/eliminar_material/', views.eliminar_material, name='eliminar_material'),
    path('stock/<pk>/editar_mat/', views.editar_material, name='editar_material'),

    path('stock/nuevo_proveedor/', views.nuevo_proveedor, name='nuevo_proveedor'),
    path('stock/listado_proveedores/', views.listado_proveedores, name='listado_proveedores'),
    path('stock/<pk>/grabar_proveedor/', views.grabar_proveedor, name='grabar_proveedor'),
    path('stock/<pk>/detalle_proveedor/', views.detalle_proveedor, name='detalle_proveedor'),
    path('stock/<pk>/eliminar_proveedor/', views.eliminar_proveedor, name='eliminar_proveedor'),
    path('stock/<pk>/editar_prov/', views.editar_proveedor, name='editar_proveedor'),

    path('stock/nuevo_egreso/', views.nuevo_egreso, name='egreso_materiales'),
    path('stock/listado_egresos/', views.listado_egresos, name='listado_egresos'),
    path('stock/<pk>/grabar_egreso/', views.grabar_egreso, name='grabar_egreso'),
    path('stock/<pk>/detalle_egreso/', views.detalle_egreso, name='detalle_egreso'),
    path('stock/<pk>/eliminar_egreso/', views.eliminar_egreso, name='eliminar_egreso'),
    path('stock/<pk>/editar_egreso/', views.editar_egreso, name='editar_egreso'),
    path('stock/<pk>/carga_articulo_egreso/', views.egreso_articulos, name='carga_articulo_out'),
    path('stock/<pk>/editar_egreso_art/', views.eliminar_egr_art, name='eliminar_egreso_art'),

    path('stock/nuevo_ingreso/', views.nuevo_ingreso, name='ingreso_materiales'),
    path('stock/listado_ingresos/', views.listado_ingresos, name='listado_ingresos'),
    path('stock/<pk>/grabar_ingreso/', views.grabar_ingreso, name='grabar_ingreso'),
    path('stock/<pk>/detalle_ingreso/', views.detalle_ingreso, name='detalle_ingreso'),
    path('stock/<pk>/eliminar_ingreso/', views.eliminar_ingreso, name='eliminar_ingreso'),
    path('stock/<pk>/editar_ingreso/', views.editar_ingreso, name='editar_ingreso'),
    path('stock/<pk>/carga_articulo_ingreso/', views.ingreso_articulos, name='carga_articulo_in'),
    path('stock/<pk>/editar_ingreso_art/', views.eliminar_ing_art, name='eliminar_ingreso_art'),

    path('stock/nuevo_precio/', views.nuevo_precio, name='nuevo_precio'),
    path('stock/<pk>/listado_precios/', views.listado_precios, name='listado_precios'),
    path('stock/<pk>/grabar_precio/', views.grabar_precio, name='grabar_precio'),
    path('stock/<pk>/eliminar_precio/', views.eliminar_precio, name='eliminar_precio'),

    path('stock/exportar_egreso/', views.exportar_egresos, name='exportar_egresos'),
    path('stock/exportar_ingreso/', views.exportar_ingresos, name='exportar_ingresos'),
    # DEB. AUT.
    path('fava/alta/', views.alta_fava, name='alta_fava'),
    path('fava/<pk>/grabar/', views.grabar_fava, name='grabar_fava'),
    path('fava/<pk>/', views.detalle_fava, name='detalle_fava'),
    path('fava/<pk>/eliminar_alta/', views.eliminar_fava, name='eliminar_fava'),
    path('arch_fava/', views.fava_files, name='archs_fava'),
    path('debdirect/alta/', views.alta_deb, name='alta_debdirect'),
    path('debdirect/<pk>/grabar/', views.grabar_deb, name='grabar_debdirect'),
    path('debdirect/<pk>/', views.detalle_deb, name='detalle_debdirect'),
    path('debdirect/<pk>/eliminar_alta/', views.eliminar_deb, name='eliminar_debdirect'),
    path('arch_bind/', views.deb_files, name='arch_bind'),
    path('debdirect/', views.lista_deb_direct, name='lista_deb_direct'),

    # RRHH
    path('rrhh/vacaciones/', views.vacaciones, name='vacaciones'),
    path('rrhh/<pk>/vacaciones/', views.detalle_empleado, name='detalle_empleado'),
    path('rrhh/<pk>/novedades/', views.carga_novedad, name='carga_novedad'),
    path('rrhh/nuevo_empleado/', views.alta_empleado, name='nuevo_empleado'),
    path('rrhh/<int:pk>/editar_empleado/', views.editar_empleado, name='editar_empleado'),
    path('rrhh/<int:pk>/editar_novedad/', views.editar_novedad, name='editar_novedad'),

    path('reclamos_correo/', views.reclamos_correo, name='reclamos_correo'),
    path('reclamos_correo/<pk>/eliminar_rec_correo/', views.eliminar_rec_correo, name='eliminar_rec_correo'),
    path('reclamos_correo/reporte', views.reporte_rec_correo, name='reporte_rec_correo'),

    path('arch_inter_muni/', views.arch_muni, name='arch_inter_muni'),
    path('cons_ctas/', views.cons_ctas, name='cons_ctas'),
    path('herramientas/', views.genera_link_pf, name='link_pf'),
    path('herramientas/simulador/', views.calculadora_intereses, name='calculadora_intereses'),
    path('desc_percibido/', views.desc_percibido, name='desc_percibido'),
    # re_path(r'^material-autocomplete/$', views.ArtSearch.as_view(), name='material-autocomplete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
